<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\OperationalExpenseConfig;

class OperationalExpenseConfigSeeder extends Seeder
{    
    public function run(): void
    {
        $configurations = [
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Aucallama',
                'destination_point' => 'Callao',
                'tolls' => 124.80,
                'loading_expenses' => 15.00,
                'variable_salary' => 50.00,
                'operations_manager' => 6.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Aucallama',
                'destination_point' => 'Salinas',
                'tolls' => 62.40,
                'loading_expenses' => 15.00,
                'variable_salary' => 50.00,
                'operations_manager' => 6.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Aucallama',
                'destination_point' => 'Chancay',
                'tolls' => 62.40,
                'loading_expenses' => 15.00,
                'variable_salary' => 50.00,
                'operations_manager' => 6.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Vegueta',
                'destination_point' => 'Callao',
                'tolls' => 249.60,
                'loading_expenses' => 15.00,
                'variable_salary' => 80.00,
                'operations_manager' => 12.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Vegueta',
                'destination_point' => 'Salinas',
                'tolls' => 187.20,
                'loading_expenses' => 15.00,
                'variable_salary' => 80.00,
                'operations_manager' => 12.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Vegueta',
                'destination_point' => 'Chancay',
                'tolls' => 187.20,
                'loading_expenses' => 15.00,
                'variable_salary' => 80.00,
                'operations_manager' => 12.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Almacén',
                'arrival_location' => 'Cañete',
                'destination_point' => 'Callao',
                'tolls' => 325.20,
                'loading_expenses' => 15.00,
                'variable_salary' => 120.00,
                'operations_manager' => 12.00,
                'security' => 10.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Aucallama',
                'destination_point' => 'Callao',
                'tolls' => 62.42,
                'loading_expenses' => 20.00,
                'variable_salary' => 50.00,
                'operations_manager' => 6.00,
                'security' => 16.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Aucallama',
                'destination_point' => 'Salinas',
                'tolls' => 62.40,
                'loading_expenses' => 20.00,
                'variable_salary' => 50.00,
                'operations_manager' => 6.00,
                'security' => 16.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Aucallama',
                'destination_point' => 'Chancay',
                'tolls' => 62.40,
                'loading_expenses' => 20.00,
                'variable_salary' => 50.00,
                'operations_manager' => 6.00,
                'security' => 16.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Vegueta',
                'destination_point' => 'Callao',
                'tolls' => 249.60,
                'loading_expenses' => 20.00,
                'variable_salary' => 80.00,
                'operations_manager' => 12.00,
                'security' => 16.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Vegueta',
                'destination_point' => 'Salinas',
                'tolls' => 187.20,
                'loading_expenses' => 20.00,
                'variable_salary' => 80.00,
                'operations_manager' => 12.00,
                'security' => 16.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Vegueta',
                'destination_point' => 'Chancay',
                'tolls' => 187.20,
                'loading_expenses' => 20.00,
                'variable_salary' => 80.00,
                'operations_manager' => 12.00,
                'security' => 16.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Apm',
                'arrival_location' => 'Quimpac',
                'destination_point' => 'Callao',
                'tolls' => 0.00,
                'loading_expenses' => 20.00,
                'variable_salary' => 40.00,
                'operations_manager' => 0.00,
                'security' => 0.00,
            ],
            [
                'departure_point' => 'Callao',
                'departure_location' => 'Quimpac',
                'arrival_location' => 'Salinas',
                'destination_point' => 'Salinas',
                'tolls' => 62.40,
                'loading_expenses' => 15.00,
                'variable_salary' => 60.00,
                'operations_manager' => 0.00,
                'security' => 0.00,
            ],
            [
                'departure_point' => 'Salinas',
                'departure_location' => 'Salinas',
                'arrival_location' => 'Paramonga',
                'destination_point' => 'Salinas',
                'tolls' => 124.80,
                'loading_expenses' => 15.00,
                'variable_salary' => 80.00,
                'operations_manager' => 0.00,
                'security' => 0.00,
            ],
            [
                'departure_point' => 'Salinas',
                'departure_location' => 'Salinas',
                'arrival_location' => 'Quimpac',
                'destination_point' => 'Salinas',
                'tolls' => 124.80,
                'loading_expenses' => 15.00,
                'variable_salary' => 80.00,
                'operations_manager' => 0.00,
                'security' => 0.00,
            ],
            [
                'departure_point' => 'Salinas',
                'departure_location' => 'Salinas',
                'arrival_location' => 'Quimpac',
                'destination_point' => 'Callao',
                'tolls' => 62.40,
                'loading_expenses' => 15.00,
                'variable_salary' => 80.00,
                'operations_manager' => 0.00,
                'security' => 0.00,
            ],
        ];

        foreach ($configurations as $config) {
            OperationalExpenseConfig::create($config);
        }

        $this->command->info('Se crearon ' . count($configurations) . ' configuraciones de gastos operativos.');
    }
}
