<?php

return [
    'departamentos' => [
        '01' => 'AMAZONAS',
        '02' => 'ÁNCASH',
        '03' => 'APURÍMAC',
        '04' => 'AREQUIPA',
        '05' => 'AYACUCHO',
        '06' => 'CAJAMARCA',
        '07' => 'CALLAO',
        '08' => 'CUSCO',
        '09' => 'HUANCAVELICA',
        '10' => 'HUÁNUCO',
        '11' => 'ICA',
        '12' => 'JUNÍN',
        '13' => 'LA LIBERTAD',
        '14' => 'LAMBAYEQUE',
        '15' => 'LIMA',
        '16' => 'LORETO',
        '17' => 'MADRE DE DIOS',
        '18' => 'MOQUEGUA',
        '19' => 'PASCO',
        '20' => 'PIURA',
        '21' => 'PUNO',
        '22' => 'SAN MARTÍN',
        '23' => 'TACNA',
        '24' => 'TUMBES',
        '25' => 'UCAYALI',
    ],

    'provincias' => [
        '15' => [ // LIMA
            '01' => 'LIMA',
            '02' => 'BARRANCA',
            '03' => 'CAJATAMBO',
            '04' => 'CANTA',
            '05' => 'CAÑETE',
            '06' => 'HUARAL',
            '07' => 'HUAROCHIRÍ',
            '08' => 'HUAURA',
            '09' => 'OYÓN',
            '10' => 'YAUYOS',
        ],
        '20' => [ // PIURA
            '01' => 'PIURA',
            '02' => 'AYABACA',
            '03' => 'HUANCABAMBA',
            '04' => 'MORROPÓN',
            '05' => 'PAITA',
            '06' => 'SULLANA',
            '07' => 'TALARA',
            '08' => 'SECHURA',
        ],
        // Agregar más provincias según necesidad...
    ],

    'distritos' => [
        '1501' => [ // LIMA - LIMA
            '01' => 'LIMA',
            '02' => 'ANCÓN',
            '03' => 'ATE',
            '04' => 'BARRANCO',
            '05' => 'BREÑA',
            '06' => 'CARABAYLLO',
            '07' => 'CHACLACAYO',
            '08' => 'CHORRILLOS',
            '09' => 'CIENEGUILLA',
            '10' => 'COMAS',
            '11' => 'EL AGUSTINO',
            '12' => 'INDEPENDENCIA',
            '13' => 'JESÚS MARÍA',
            '14' => 'LA MOLINA',
            '15' => 'LA VICTORIA',
            '16' => 'LINCE',
            '17' => 'LOS OLIVOS',
            '18' => 'LURIGANCHO',
            '19' => 'LURIN',
            '20' => 'MAGDALENA DEL MAR',
            '21' => 'PUEBLO LIBRE',
            '22' => 'MIRAFLORES',
            '23' => 'PACHACÁMAC',
            '24' => 'PUCUSANA',
            '25' => 'PUENTE PIEDRA',
            '26' => 'PUNTA HERMOSA',
            '27' => 'PUNTA NEGRA',
            '28' => 'RÍMAC',
            '29' => 'SAN BARTOLO',
            '30' => 'SAN BORJA',
            '31' => 'SAN ISIDRO',
            '32' => 'SAN JUAN DE LURIGANCHO',
            '33' => 'SAN JUAN DE MIRAFLORES',
            '34' => 'SAN LUIS',
            '35' => 'SAN MARTÍN DE PORRES',
            '36' => 'SAN MIGUEL',
            '37' => 'SANTA ANITA',
            '38' => 'SANTA MARÍA DEL MAR',
            '39' => 'SANTA ROSA',
            '40' => 'SANTIAGO DE SURCO',
            '41' => 'SURQUILLO',
            '42' => 'VILLA EL SALVADOR',
            '43' => 'VILLA MARÍA DEL TRIUNFO',
        ],
        '2001' => [ // PIURA - PIURA
            '01' => 'PIURA',
            '02' => 'CASTILLA',
            '03' => 'CATACAOS',
            '04' => 'CURA MORI',
            '05' => 'EL TALLÁN',
            '06' => 'LA ARENA',
            '07' => 'LA UNIÓN',
            '08' => 'LAS LOMAS',
            '09' => 'TAMBO GRANDE',
        ],
        // Agregar más distritos según necesidad...
    ],
];
